query GetCartItems {
  cartItems {
    id
    uid
    productId
    title
    price
    quantity
  }
}

mutation AddCartItems($items: [AddCartItemInput!]!) {
  addCartItems(items: $items) {
    id
    uid
    productId
    title
    price
    quantity
    product {
      id
      stock
    }
  }
}
{
  "items": [
    {
      "productId": "product1",
      "title": "iPad 4 Mini",
      "price": 500.01,
      "quantity": 1
    },
    {
      "productId": "product2",
      "title": "Fire HD 8 Tablet",
      "price": 80.99,
      "quantity": 2
    }
  ]
}

mutation AddCartItems {
  addCartItems(items: [
    {
      productId: "product1"
      title: "iPad 4 Mini"
      price: 500.01
      quantity: 1
    },
    {
      productId: "product2"
      title: "Fire HD 8 Tablet"
      price: 80.99
      quantity: 2
    }
  ]) {
    id
    uid
    productId
    title
    price
    quantity
    product {
      id
      stock
    }
  }
}

mutation UpdateCartItems {
  updateCartItems(items: [
    {
      id: "cartItem1"
      quantity: 1
    },
    {
      id: "cartItem2"
      quantity: 2
    }
  ]) {
    id
    uid
    productId
    title
    price
    quantity
    product {
      id
      stock
    }
  }
}

mutation UpdateCartItems($items: [UpdateCartItemInput!]!) {
  updateCartItems(items: $items) {
    id
    uid
    productId
    title
    price
    quantity
    product {
      id
      stock
    }
  }
}
{
  "items": [
    {
      "id": "cartItem1",
      "quantity": 1
    },
    {
      "id": "cartItem2",
      "quantity": 2
    }
  ]
}

mutation RemoveCartItems {
  removeCartItems(ids: [
    "cartItem1"
    "cartItem2"
  ]) {
    id
    uid
    productId
    title
    price
    quantity
  }
}

mutation RemoveCartItems($ids: [ID!]!) {
  removeCartItems(ids: $ids) {
    id
    uid
    productId
    title
    price
    quantity
  }
}
{
  "ids": ["cartItem1", "cartItem2"]
}

mutation CheckoutCart {
  checkoutCart
}

mutation Example1 {
  example1(item:
    {
      id: "cartItem1"
      quantity: -1
    }
  )
}

mutation Example2 {
  example2(items: [
    {
      id: "cartItem1"
      quantity: -1
    }
  ])
}
