import {
  ClosePopup,
  Dialog,
  Loading,
  Notify,
  QAvatar,
  QBar,
  QBreadcrumbs,
  QBreadcrumbsEl,
  QBtn,
  QBtnToggle,
  QCard,
  QCardActions,
  QCardSection,
  QCheckbox,
  QDialog,
  QDrawer,
  QExpansionItem,
  QForm,
  QHeader,
  QIcon,
  QImg,
  QInput,
  QItem,
  QItemLabel,
  QItemSection,
  QLayout,
  QLinearProgress,
  QList,
  QMenu,
  QPage,
  QPageContainer,
  QRouteTab,
  QScrollArea,
  QSeparator,
  QSpace,
  QSplitter,
  QTab,
  QTable,
  QTabs,
  QTd,
  QTh,
  QToolbar,
  QToolbarTitle,
  QTooltip,
  QTr,
  Quasar,
  Ripple,
} from 'quasar'
import Vue from 'vue'

export namespace quasar {
  export function setup() {
    Vue.use(Quasar, {
      components: {
        QAvatar,
        QBar,
        QBreadcrumbs,
        QBreadcrumbsEl,
        QBtn,
        QBtnToggle,
        QCard,
        QCardActions,
        QCardSection,
        QCheckbox,
        QDialog,
        QDrawer,
        QExpansionItem,
        QForm,
        QHeader,
        QIcon,
        QImg,
        QInput,
        QItem,
        QItemLabel,
        QItemSection,
        QLayout,
        QLinearProgress,
        QList,
        QMenu,
        QPage,
        QPageContainer,
        QRouteTab,
        QScrollArea,
        QSeparator,
        QSpace,
        QSplitter,
        QTab,
        QTable,
        QTabs,
        QTd,
        QTh,
        QToolbar,
        QToolbarTitle,
        QTooltip,
        QTr,
      },

      config: {
        notify: {},
        loading: {},
      },

      directives: {
        ClosePopup,
        Ripple,
      },

      plugins: {
        Dialog,
        Loading,
        Notify,
      },
    })
  }

  export function setupExtras() {
    require('@quasar/extras/roboto-font/roboto-font.css')
    require('@quasar/extras/material-icons/material-icons.css')
    require('@quasar/extras/fontawesome-v5/fontawesome-v5.css')
  }
}
