query GetUserStorageBasePath {
  userStorageBasePath
}

query GetUserStorageDirNodes {
  userStorageDirNodes {
    nodeType
    name
    dir
    path
  }
}

query GetUserStorageDirNodes {
  userStorageDirNodes(dirPath: "dir1") {
    nodeType
    name
    dir
    path
  }
}

query GetUserStorageDirNodes($dirPath: String) {
  userStorageDirNodes(dirPath: $dirPath) {
    nodeType
    name
    dir
    path
  }
}
{
  "dirPath": "dir1"
}

mutation CreateUserStorageDirs {
  createUserStorageDirs(dirPaths: ["dir1/dir1_1"]) {
    nodeType
    name
    dir
    path
  }
}

mutation CreateUserStorageDirs($dirPaths: [String!]!) {
  createUserStorageDirs(dirPaths: $dirPaths) {
    nodeType
    name
    dir
    path
  }
}
{
  "dirPaths": [
    "dir1/dir1_1",
    "dir1/dir1_1/dir1_1_1",
    "dir1/dir1_1/dir1_1_2",
    "dir2/dir2_1"
  ]
}

mutation RemoveUserStorageFileNodes {
  removeUserStorageFiles(filePaths: ["docs/fileA.txt"]) {
    nodeType
    name
    dir
    path
  }
}

mutation RemoveUserStorageFileNodes($filePaths: [String!]!) {
  removeUserStorageFiles(filePaths: $filePaths) {
    nodeType
    name
    dir
    path
  }
}
{
  "filePaths": ["docs/fileA.txt"]
}

mutation RemoveUserStorageDirNodes {
  removeUserStorageDir(dirPath: "dir1/dir1_1") {
    nodeType
    name
    dir
    path
  }
}

mutation RemoveUserStorageDirNodes($dirPath: String!) {
  removeUserStorageDir(dirPath: $dirPath) {
    nodeType
    name
    dir
    path
  }
}
{
  "dirPath": "dir1/dir1_1"
}

query GetSignedUploadUrls {
  signedUploadUrls(inputs: [
    { filePath: "images/family.png", contentType: "image/png" }
  ])
}

query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) {
  signedUploadUrls(inputs: $inputs)
}
{
  "inputs": [
    {
      "filePath": "images/family.png",
      "contentType": "image/png"
    }
  ]
}
