query GetProducts {
  products(ids: ["product1", "product3"]) {
    id
    title
    price
    stock
  }
}

query GetProducts($ids: [ID!]) {
  products(ids: $ids) {
    id
    title
    price
    stock
  }
}
{
  "ids": ["product1", "product3"]
}
